jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Firebase authentication
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "$HOME/service-account.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json" >> $GITHUB_ENV
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: ordersapp-82d1c
