name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Можно заменить, если хотите деплой с другой ветки

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ORDERSAPP_82D1C }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > service-account.json
          firebase deploy --token "$FIREBASE_SERVICE_ACCOUNT" --project ordersapp-82d1c
